# Generated by Django 4.1.4 on 2023-01-04 17:09

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.TextField()),
                ('icon', models.URLField()),
                ('bg', models.URLField()),
                ('status', models.TextField()),
                ('plat_form', models.TextField(default='None')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('friend_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game_id', models.CharField(max_length=100, unique=True)),
                ('status', models.TextField()),
                ('players', models.JSONField()),
                ('createdAt', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game', models.TextField()),
                ('players_A', models.CharField(max_length=100)),
                ('players_B', models.CharField(max_length=100)),
                ('result', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('game_timestamp', models.IntegerField(default=0)),
                ('playedAt', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_picture', models.URLField(default='https://marketplace.canva.com/EAE93oDu61A/1/0/1600w/canva-purple-blue-neon-gaming-desktop-backgrounds-PWYZmwkPtUg.jpg')),
                ('username', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('bio', models.CharField(default='You Bio here...', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.TextField(default='0')),
                ('country', models.TextField()),
                ('birthday', models.TextField()),
                ('joinedAt', models.DateField(default=datetime.date.today)),
                ('main_id', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('totalpts', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
