# Generated by Django 4.1.4 on 2022-12-23 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0002_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
