# Generated by Django 4.1.4 on 2022-12-29 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0003_delete_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game_id', models.CharField(max_length=100)),
                ('status', models.TextField()),
                ('players', models.JSONField()),
                ('createdAt', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
