# Generated by Django 4.1.4 on 2022-12-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0004_lobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='game_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
