# Generated by Django 4.1.4 on 2022-12-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0005_alter_lobby_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_picture',
            field=models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUzvnAjmVtNv-cX4DuPQ8m-Hems1FMzzVJhw&usqp=CAU'),
        ),
    ]
