# Generated by Django 4.1.4 on 2023-01-02 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0006_users_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='friend_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user2_Users', to='bet.users'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user1_Users', to='bet.users'),
        ),
    ]
