# Generated by Django 4.1.4 on 2023-01-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0009_alter_friends_friend_id_alter_friends_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='friend_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='friends',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
